IuchBundle\Entity\Badge:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        remis:
            type: boolean
        date_remise:
            type: datetime
            column: date_remise
        date_rendu:
            type: datetime
            column: date_rendu
            nullable: true

    oneToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        intervenant:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: intervenant_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
