IuchBundle\Entity\Charte:
    type:   entity
    repositoryClass: IuchBundle\Entity\CharteRepository
    fields:

        id:
            type:       integer
            id:         true
            generator:  { strategy: AUTO }

        nom:
            type:       string
            length:     255

        file_name:
            type: string
            length: 255
            nullable: true

        charte_file:
            type: string
            length: 255

        description:
            type: string
            length: 255
            nullable: true

        obligatoire:
            type: boolean

    manyToOne:
        service:
            targetEntity: Service
            joinColumn:
                name: service_id
                referencedColumnName: id
            cascade: ["persist", "merge"]

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
