IuchBundle\Entity\Charte_utilisateur:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        signature:
            type: boolean
        dateSignature:
            type: datetime
            column: date_signature

    manyToOne:
        charte:
            targetEntity: Charte
            joinColumn:
                name: charte_id
                referencedColumnName: id
                onDelete: SET NULL

        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            orphanRemoval: true
            joinColumn:
                name: utilisateur_id
                referencedColumnName: id
                onDelete: cascade

    lifecycleCallbacks: {  }
