IuchBundle\Entity\Service:
    type: entity
    repositoryClass: IuchBundle\Entity\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        uf:
            type: string
            length: 4
        email:
            type: string
            length: 255
        telephone:
            type: string
            length: 64

# Relation for chefService
    oneToMany:
        users:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            mappedBy: service

    lifecycleCallbacks: {  }