IuchBundle\Entity\Service:
    type: entity
    table: null
    repositoryClass: IuchBundle\Entity\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        email:
            type: string
            length: 255
        telephone:
            type: string
            length: 64
        chef_service:
            type: integer
            nullable: true

    oneToMany:
        users:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            mappedBy: user

    lifecycleCallbacks: {  }
