IuchBundle\Entity\Tenue:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date_donnee:
            type: datetime
            column: date_donnee
        nombre_donne:
            type: integer
            column: nombre_donne
        date_rendu:
            type: datetime
            column: date_rendu
            nullable: true
        nombre_rendu:
            type: integer
            column: nombre_rendu
            nullable: true
        commentaire:
            type: text
            nullable: true

    manyToOne:
        intervenant:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: intervenant_id
                referencedColumnName: id
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        type:
            targetEntity: IuchBundle\Entity\TypeTenue
            joinColumn:
                name: type_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
