IuchBundle\Entity\TypeTenue:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
            unique: true

    lifecycleCallbacks: {  }