IuchBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: IuchBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
#    manyToMany:
#        chartes:
#            targetEntity: Charte
#            inversedBy: users
#            joinTable:
#                name: users_chartes
#                joinColumns:
#                    user_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    charte_id:
#                        referencedColumnName: id
    lifecycleCallbacks: {  }
