IuchBundle\Entity\WelcomeMail:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sujet:
            type: string
            length: 255
        corps:
            type: text
    lifecycleCallbacks: {  }
