iuch_homepage:
    path: /
    defaults: { _controller: "IuchBundle:Homepage:Index" }
    methods:  [GET]

iuch_signature:
    path: /signature/{charte_id}
    defaults: { _controller: "IuchBundle:Signature:Signature" }
    methods:  [GET]

iuch_create_signature:
    path: /create_signature/{charte_id}
    defaults: { _controller: "IuchBundle:Signature:CreateSignature" }
    methods:  [POST, GET]

iuch_get_charte:
    path: /charte/{charte_file}
    defaults: { _controller: "IuchBundle:Signature:getCharte" }
    methods:  [GET]

iuch_get_photo:
    path: /photo/{photo_id}
    defaults: { _controller: "IuchBundle:Photo:getPhoto" }
    methods:  [GET]

iuch_trombinoscope:
    path: /trombinoscope
    defaults: { _controller: "IuchBundle:Photo:trombinoscope" }
    methods:  [GET]

iuch_statistiques:
    path: /statistiques
    defaults:
    methods:  [GET]
