iuch_homepage:
    path: /
    defaults: { _controller: "IuchBundle:Homepage:Index" }

iuch_signature:
    path: /signature/{charte_id}
    defaults: { _controller: "IuchBundle:Signature:Signature" }

iuch_create_signature:
    path: /create_signature/{charte_id}
    defaults: { _controller: "IuchBundle:Signature:CreateSignature" }
    methods:  [POST, GET]

iuch_get_charte:
    path: /charte/{charte_file}
    defaults: { _controller: "IuchBundle:Signature:getCharte" }
    methods:  [GET]