services:
#    iuch.example:
#        class: IuchBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.photo:
        class: IuchBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.photo", label: "Photos", label_catalogue: "IuchBundle" }
        arguments:
            - ~
            - IuchBundle\Entity\Photo
            - ~

    sonata.service:
        class: IuchBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Services", label_catalogue: "IuchBundle" }
        arguments:
            - ~
            - IuchBundle\Entity\Service
            - ~

    sonata.fonction:
        class: IuchBundle\Admin\FonctionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Fonctions", label_catalogue: "IuchBundle" }
        arguments:
            - ~
            - IuchBundle\Entity\Fonction
            - ~
    sonata.charte:
        class: IuchBundle\Admin\CharteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.chartes", label: "Chartes" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte
            - ~
    sonata.charte_utilisateur:
        class: IuchBundle\Admin\CharteUtilisateurAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.chartes", label: "Chartes signées" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte_utilisateur
            - ~

    sonata.tenue:
        class: IuchBundle\Admin\TenueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.tenue", label: "Tenues données/rendues" }
        arguments:
            - ~
            - IuchBundle\Entity\Tenue
            - ~

    sonata.type_tenue:
        class: IuchBundle\Admin\TypeTenueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.tenue", label: "Type de tenue" }
        arguments:
            - ~
            - IuchBundle\Entity\TypeTenue
            - ~

    iuch.tenue_listener:
        class: IuchBundle\Listener\TenueListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.materiel:
        class: IuchBundle\Admin\MaterielAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.keys", label: "Matériels donnés/rendus" }
        arguments:
            - ~
            - IuchBundle\Entity\Materiel
            - ~

    iuch.materiel_listener:
        class: IuchBundle\Listener\MaterielListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.type_materiel:
        class: IuchBundle\Admin\TypeMaterielAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "iuch.group.keys", label: "Type de matériel" }
        arguments:
            - ~
            - IuchBundle\Entity\TypeMateriel
            - ~

    sonata.block.service.stat:
        class: IuchBundle\Block\StatBlockService
        arguments: [ "sonata.block.service.stat", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    sonata.block.service.statmateriel:
        class: IuchBundle\Block\StatMaterielBlockService
        arguments: [ "sonata.block.service.statmateriel", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    sonata.block.service.statlastuser:
        class: IuchBundle\Block\StatLastUserBlockService
        arguments: [ "sonata.block.service.statlastuser", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    sonata.block.service.stattenue:
        class: IuchBundle\Block\StatTenueBlockService
        arguments: [ "sonata.block.service.stattenue", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    assetic.filter.twig:
        class: IuchBundle\Filter\TwigFilter
        arguments:
            - @templating
        tags:
            - { name: "assetic.filter", alias: "twig"}
