services:
#    iuch.example:
#        class: IuchBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.Photo:
        class: IuchBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Photos", label: "Photos" }
        arguments:
            - ~
            - IuchBundle\Entity\Photo
            - ~

    sonata.Service:
        class: IuchBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Services/Fonctions", label: "Services" }
        arguments:
            - ~
            - IuchBundle\Entity\Service
            - ~

    sonata.Fonction:
        class: IuchBundle\Admin\FonctionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Services/Fonctions", label: "Fonctions" }
        arguments:
            - ~
            - IuchBundle\Entity\Fonction
            - ~
    sonata.Charte:
        class: IuchBundle\Admin\CharteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chartes", label: "Chartes" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte
            - ~
    sonata.CharteUtilisateur:
        class: IuchBundle\Admin\CharteUtilisateurAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chartes", label: "Chartes signée" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte_utilisateur
            - ~

    sonata.Tenue:
        class: IuchBundle\Admin\TenueAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion des tenues", label: "Tenues données/rendues" }
        arguments:
            - ~
            - IuchBundle\Entity\Tenue
            - ~

    iuch.tenue_listener:
        class: IuchBundle\Listener\TenueListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.Cle:
        class: IuchBundle\Admin\CleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion clés/badges", label: "Clés données/rendues" }
        arguments:
            - ~
            - IuchBundle\Entity\Cle
            - ~

    iuch.cle_listener:
        class: IuchBundle\Listener\CleListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.Badge:
        class: IuchBundle\Admin\BadgeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gestion clés/badges", label: "Badge donnés/rendus" }
        arguments:
            - ~
            - IuchBundle\Entity\Badge
            -

    iuch.badge_listener:
        class: IuchBundle\Listener\BadgeListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    sonata.block.service.stat:
        class: IuchBundle\Block\StatBlockService
        arguments: [ "sonata.block.service.stat", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    sonata.block.service.statuser:
        class: IuchBundle\Block\StatUserBlockService
        arguments: [ "sonata.block.service.statuser", @templating, @sonata.admin.pool, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: sonata.block }

    assetic.filter.twig:
        class: IuchBundle\Filter\TwigFilter
        arguments:
            - @templating
        tags:
            - { name: "assetic.filter", alias: "twig"}

