services:
#    iuch.example:
#        class: IuchBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.Charte:
        class: IuchBundle\Admin\CharteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chartes", label: "Chartes" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte
            - ~
    sonata.Service:
        class: IuchBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Services", label: "Services" }
        arguments:
            - ~
            - IuchBundle\Entity\Service
            - ~

    sonata.Fonction:
        class: IuchBundle\Admin\FonctionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Fonctions", label: "Fonctions" }
        arguments:
            - ~
            - IuchBundle\Entity\Fonction
            - ~

    sonata.CharteUtilisateur:
        class: IuchBundle\Admin\CharteUtilisateurAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chartes signées", label: "Charte signée" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte_utilisateur
            - ~

    sonata.Tenue:
            class: IuchBundle\Admin\TenueAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Gestion des tenues", label: "Admin donnée/rendue" }
            arguments:
                - ~
                - IuchBundle\Entity\Tenue
                - ~

