services:
#    iuch.example:
#        class: IuchBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.Charte:
        class: IuchBundle\Admin\CharteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Chartes", label: "Chartes" }
        arguments:
            - ~
            - IuchBundle\Entity\Charte
            - ~