# src/AppBundle/Resources/config/validation.yml
IuchBundle\Entity\Charte:
    properties:
        file:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Please upload a valid PDF

IuchBundle\Entity\Photo:
    properties:
        photo:
            - Image:
                maxSize: 1024k
                minWidth: 200
                maxWidth: 600
                minHeight: 200
                maxHeight: 600