# src/AppBundle/Resources/config/validation.yml
IuchBundle\Entity\Charte:
    properties:
        file:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Please upload a valid PDF

IuchBundle\Entity\Photo:
    properties:
        photo_file:
            - Image:
                maxSize: 1024k
                minWidth: 100
                maxWidth: 1000
                minHeight: 100
                maxHeight: 1000

IuchBundle\Entity\Service:
    properties:
        uf:
         - Regex :
            pattern: '/\d{4}/'
            message: Veuillez rentrer un uf valide (4 chiffres).
        email:
            - Email:
                message: Veuillez rentrer un email valide.
                checkMX: true
        telephone:
            - Regex :
                pattern: '/^0[1-9]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})|((-[0-9]{2}){4})$/'
                message: Veuillez rentrer un numéro de téléphone valide. Ex : 0145678950 | 01 45 67 89 50 | 01-45-67-89-50 | 01.45.67.89.50
