# src/AppBundle/Resources/config/validation.yml
IuchBundle\Entity\Charte:
    properties:
        file:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Veuillez télécharger un fichier PDF valide.

IuchBundle\Entity\Photo:
    properties:
        photo_file:
            - Image:
                maxSize: 1024k
                minWidth: 100
                maxWidth: 1000
                minHeight: 100
                maxHeight: 1000

IuchBundle\Entity\Service:
    properties:
        uf:
         - Regex :
            pattern: '/\d{4}/'
            message: Veuillez rentrer un uf valide (4 chiffres).
        email:
            - Email:
                message: Veuillez rentrer un email valide.
        telephone:
            - Regex :
                pattern: '/^0[1-9]([-\/. ]?[0-9]{2}){4}$/'
                message: Veuillez rentrer un numéro de téléphone valide. Ex : 0145678950 | 01 45 67 89 50 | 01-45-67-89-50 | 01.45.67.89.50
        chef_service:
            - NotNull: ~
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [chef_service]
            message: "L'utilisateur est déjà chef de service"

Application\Sonata\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'Il y a déjà un utilisateur avec ce matricule'
    properties:
        username:
            - Regex:
                pattern : '/^[0-9]{0,6}$/'
                message: Le matricule doit être composé de maximum 6 chiffres.

        zip:
            - Length:
                max: 5
            - Regex:
                pattern: '/^[0-9]{5}$/'
                message: Veuillez rentrer un code postal valide.
        email:
            - Email:
                message: Veuillez rentrer un email valide.
        phone:
            - Regex :
                pattern: '/^0[1-9]([-\/. ]?[0-9]{2}){4}$/'
                message: Veuillez rentrer un numéro de téléphone valide. Ex : 0145678950 | 01 45 67 89 50 | 01-45-67-89-50 | 01.45.67.89.50

IuchBundle\Entity\TypeMateriel:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: type
            message: Le type existe déjà

IuchBundle\Entity\TypeTenue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: type
            message: Le type existe déjà

IuchBundle\Entity\Materiel:
    getters:
        userEnabled:
            - 'IsTrue':
                message: L'utilisateur n'est pas activé, veuillez contactez le service RH

IuchBundle\Entity\Tenue:
    getters:
        userEnabled:
            - 'IsTrue':
                message: L'utilisateur n'est pas activé, veuillez contactez le service RH

FOS\UserBundle\Form\Model\ChangePassword:
    properties:
        new:
            - Regex:
                pattern: "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{6,16}$/"
                message: "Le mot de passe doit être compris entre 6 et 16 caractères avec au minimum 1 minuscule, 1 majuscule et 1 chiffre."
                groups: [ChangePassword, ResetPassword]
