# src/AppBundle/Resources/config/validation.yml
IuchBundle\Entity\Charte:
    properties:
        file:
            - File:
                maxSize: 1024k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Please upload a valid PDF