<?php

namespace IuchBundle\Entity;

/**
 * FonctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionRepository extends \Doctrine\ORM\EntityRepository
{

}