<?php

namespace IuchBundle\Entity;

/**
 * CharteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByServices($user_service, $user_services)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('c')
            ->from($this->_entityName, 'c')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->leftJoin('c.service', 's')
            ->Where('s IN (:userService, :userServices)')
            ->orWhere('c.service is NULL')
            ->setParameter('userService', $user_service)
            ->setParameter('userServices', $user_services);
        return $queryBuilder->getQuery()->getResult();
    }
}
