<?php

namespace IuchBundle\Entity;

/**
 * Charte_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Charte_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findChartesByUserServices()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('cu')
            ->from($this->_entityName, 'cu')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('cu.charte.service is null')
            ->andWhere('cu.charte.service = cu.user.service')
            ->andWhere('cu.charte.service = cu.user.services');
        return $queryBuilder->getQuery()->getResult();
    }
}
