wcs_info_mail_infomail:
    resource: "@InfoMailBundle/Resources/config/routing/infomail.yml"
    prefix:   /infomail

wcs_info_mail_homepage:
    path:     /
    defaults: { _controller: InfoMailBundle:InfoMail:index }

wcs_info_mail_file:
    path: /{file_id}/documents
    defaults: { _controller: InfoMailBundle:File:getFile }