services:
    sonata.reset_mdp:
        class: IuchBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm }
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\User
            - Application\Sonata\AdminBundle\Controller\CRUDController